# Generated by Django 5.1 on 2024-08-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_collection_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='posts',
            field=models.ManyToManyField(blank=True, to='posts.post'),
        ),
    ]
