# Generated by Django 5.1 on 2024-08-18 14:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_collection_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
