# Generated by Django 5.1 on 2024-08-27 07:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ManyToManyField(related_name='followed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
