# Generated by Django 5.1 on 2024-08-27 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_following_follower_following_follower'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='followed',
        ),
        migrations.AddField(
            model_name='following',
            name='followed',
            field=models.ForeignKey(default=210, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='followers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
