# Generated by Django 5.1 on 2024-09-11 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_darktheme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DarkTheme',
        ),
    ]
