name: User Story for Stumblr
description: A template for the user stories for the stumblr project.
title: "[USER STORY]: "
labels: ["enhancement"]
projects: ["DajanPlackovic/3"]
assignees:
  - DajanPlackovic
body:
  - type: markdown
    attributes:
      value: |
          As a **role** I can **capability** so that **received benefit**

          Acceptance Criteria:

          - AC1
          - AC2
