name: User Story for Stumblr
description: A template for the user stories for the stumblr project.
title: "[USER STORY] "
labels: ["enhancement"]
projects: ["DajanPlackovic/3"]
assignees:
  - DajanPlackovic
body:
  - type: textarea
    id: user-story
    attributes:
      description: Enter a User Story in the proper form and Acceptence Criteria in a bulletpoint list.
      placeholder: Enter the value here
      value: |
          As a **role** I can **capability** so that **received benefit**

          Acceptance Criteria:
          - AC1
          - AC2
    validations:
      required: true
